namespace PasswordManager.Core.Models
{
    /// <summary>
    /// Shared policy for password strength (master password, vault passwords, etc.) and for passwords
    /// generated by <see cref="Services.Implementations.CryptoService.GeneratePassword"/>.
    /// Use these constants in <see cref="Validators.PasswordValidator"/> and <see cref="Validators.PasswordOptionsValidator"/>
    /// so that any generated password (with default or compatible options) always passes validation.
    /// </summary>
    internal static class PasswordPolicy
    {
        /// <summary>Minimum length. Matches PasswordOptionsValidator and CryptoService generator range.</summary>
        public const int MinLength = 8;

        /// <summary>Maximum length. Matches PasswordOptionsValidator and CryptoService generator range.</summary>
        public const int MaxLength = 128;

        /// <summary>Special characters used by the generator. Password must contain at least one of these.</summary>
        public const string SpecialCharacters = "!@#$%^&*()-_=+[]{}|;:,.<>?";
    }
}
